server:
#  port: 8081
  servlet:
  context-path: /boot

spring:
  datasource:
    hikari:
      username: root
      password: root123
#      jdbc-url: jdbc:mysql://120.26.160.119:3306/springBootGenerate
      url: jdbc:mysql://120.26.160.119:3306/springBootGenerate
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 120.26.160.119
    port: 6379
    password: root123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

person:
  name: 李青山${random.uuid}
  age: 22
  birthday: 1998/07/18