spring:
  #datasource
  datasource:
    hikari:
      username: root
      password: root123
      jdbc-url: jdbc:mysql://120.26.160.119:3306/springBootGenerate
      driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  redis:
    database: 0
    host: 120.26.160.119
    port: 6379
    password: root123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

  profiles:
    active: dev

#配置类配置信息
person:
  name: 李青山${random.uuid}
  age: 22
  birthday: 1998/07/18

#debug: true 查看自动配置报告 分析Negative matches:
#日志级别配置信息
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      generator: trace

---
spring:
  profiles: prod
server:
  port: 8082
---
spring:
  profiles: test
server:
  port: 8083